### PR TITLE
Branch ped fixes

### LINKED ISSUE #129: [PE-D][Tester D] Negative integer for cooking time is not checked
The cooking time field accepts negative integers.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: z-wenqing/ped#2

### LINKED ISSUE #133: [PE-D][Tester A] Incorrect command for list
The incorrect command of "list 42354y" still works

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: HenryGan138/ped#4

### LINKED ISSUE #135: [PE-D][Tester B] Error in URL
The URL String contain spaces but was accepted.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: paturikarthik/ped#9

### PR DESCRIPTION
**Pull request by chenxk619**
Fixes #135 , #149 , #152 relating to user URL to be valid.
Fixes #129 , #137 relating to negative calories and cook time being accepted.
Fixes #133 relating to trailing characters after the list command being accepted.

Also updated User guide, moved some outputs to constants, and added method comments

### CODE REVIEW

File: src/main/java/recipeio/InputParser.java [hunk 1]
```diff
@@ -26,12 +27,19 @@ public class InputParser {
...
+     * Most error handling in TaskList.java, with an exception for the list command.
+     * Checks are made for any trailing characters following the list command and returns an invalid command
+     * if any of such characters are found
      *
      * @param userInput input from the user in the command line.
      * @return the command keyword. e.g. add, delete.
      */
     public static String parseCommand(String userInput) {
+        //if list command with other characters trailing, returns an invalid command
+        if (userInput.startsWith("list") && userInput.length() != 4) {
```
Comment (nidhi-nayak) [inline src/main/java/recipeio/InputParser.java:39]: i think for this we should trim the userInput in case of leading spaces. also this doesn't account for an uppercase "LIST" which should work. 

try something like if userInput.tolowercase.startsWith("list") && userInput.trim().length() != 4

File: src/main/java/recipeio/CommandValidator.java [hunk 2]
```diff
@@ -279,14 +301,41 @@ public static boolean isValidAddCommand(String userInput) {
...
+     *
+     * @param userInput User's input in the command line.
+     * @return status of check.
+     */
+    public static boolean isValidURL(String userInput) {
+        String details = userInput.trim();
+        boolean isValid = true;
+
+        // Validate URL subdomain
+        if (!details.startsWith("http://") && !details.startsWith("https://") && !details.startsWith("www.")) {
```
Comment (nidhi-nayak) [inline src/main/java/recipeio/CommandValidator.java:328]: extracting the url criteria so that they are not magic literals might be a good idea!

**Review by nidhi-nayak — CHANGES_REQUESTED** [review]
Overall good, just some few minor fixes I think would be good :)

**Review by nidhi-nayak — DISMISSED** [review]
just one super quick change (so sorry i forgot to mention it before). everything else looks great to me! good job!! once you make that one line change, you should be good to merge!! :) thanks so much!
